=== StepanPilchyck/DeliveryService/config/func_view.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!ELEMENT pages (page)*>

<!ELEMENT page (func_view)*>
<!ATTLIST page
    menu_item CDATA #REQUIRED
    page_name CDATA #REQUIRED
  >

<!ELEMENT func_view EMPTY>
<!ATTLIST func_view
    name CDATA #REQUIRED
    right CDATA #REQUIRED
  >

=== StepanPilchyck/DeliveryService/config/func_view.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="func_view.xsl"?>
<!DOCTYPE pages SYSTEM "func_view.dtd">
<pages>
    <page page_name="/package/add/register" menu_item = "register">
        <func_view right="test_right1" name="name1" />
        <func_view right="name2" name="name2" />
        <func_view right="name3" name="name3" />
        <func_view right="name4" name="name4" />
        <func_view right="name5" name="name5" />
    </page>
    <page page_name="page1" menu_item = "item2">
        <func_view right="test_right1" name="name4" />
        <func_view right="test_right2" name="name1" />
        <func_view right="name2" name="name2" />
        <func_view right="test_right3" name="name3" />
        <func_view right="name5" name="name5" />
    </page>
    <page page_name="page2" menu_item = "item3">
        <func_view right="test_right3" name="name1" />
        <func_view right="name2" name="name2" />
        <func_view right="name3" name="name3" />
        <func_view right="name4" name="name4" />
        <func_view right="name5" name="name5" />
    </page>
</pages>
